kind: Service
apiVersion: v1
metadata:
  name: mysql-service
  namespace: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306

#This is for the Statefullset.yml file which creates the mysql pod for the statefull pods and this file is the service details for that pod
